source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SampleWrapperPod_Example', :exclusive => true do
  pod 'SampleWrapperPod', :path => '../'
end

target 'SampleWrapperPod_Tests', :exclusive => true do
  pod 'SampleWrapperPod', :path => '../'

  
end
